// <auto-generated />
using AnimalShelterAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterAPI.Migrations
{
    [DbContext(typeof(AnimalShelterAPIContext))]
    [Migration("20200403200135_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterAPI.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Name");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = 9,
                            Breed = "Polydactyl Turkish Angora",
                            Name = "Stella"
                        },
                        new
                        {
                            CatId = 2,
                            Age = 5,
                            Breed = "Tuxedo",
                            Name = "Charlie"
                        },
                        new
                        {
                            CatId = 3,
                            Age = 7,
                            Breed = "Tabby",
                            Name = "Tina"
                        });
                });

            modelBuilder.Entity("AnimalShelterAPI.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Name");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 15,
                            Breed = "Golden Retriever",
                            Name = "Casey"
                        },
                        new
                        {
                            DogId = 2,
                            Age = 10,
                            Breed = "Flat Coat Retriever",
                            Name = "Brian"
                        },
                        new
                        {
                            DogId = 3,
                            Age = 7,
                            Breed = "Golden Retriever",
                            Name = "Frank"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
